name: shake_shuffle_example

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_auth:
  google_sign_in:

  cupertino_icons: ^0.1.3
  google_sign_in_web: ^0.10.0+5

  # shake: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true